name: build-release
on:
  push:
    branches:
      - main
      - feature/rtc
jobs:
  build-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: "stable"
      - run: flutter pub get
      - run: flutter build web --web-renderer html
      - run: echo "F_VERSION=$(cat pubspec.yaml | grep -Po '(?<=version:\s)(.*)')" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: v$F_VERSION
          message: ""
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dieklingel_base_$F_VERSION.zip build/web
